# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
