# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180213_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='ctgry', max_length=50),
            preserve_default=False,
        ),
    ]
