# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180214_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Category'),
        ),
    ]
