# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20180220_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='img_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='img_height', null=True, upload_to='images/%Y/%m/%d', width_field='img_width'),
        ),
    ]
